apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitops-demo-app
  template:
    metadata:
      labels:
        app: gitops-demo-app
    spec:
      containers:
        - name: app
          # The GitHub Action will automatically replace this tag when you push code!
          image: takowtakow/gitops-demo:v2.0.2
          ports:
            - containerPort: 3000
