apiVersion: v1
kind: Service
metadata:
  name: gitops-demo-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080
  selector:
    app: gitops-demo-app
